# - Find OKVIS library
# Find the native OKVIS includes and library
# This module defines
#  OKVIS_INCLUDE_DIRS, where to find OKVIS.h, Set when
#                      OKVIS_INCLUDE_DIR is found.
#  OKVIS_LIBRARIES, libraries to link against to use OKVIS.
#  OKVIS_ROOT_DIR, The base directory to search for OKVIS.
#                  This can also be an environment variable.
#  OKVIS_FOUND, If false, do not try to use OKVIS.
#
# also defined, but not for general use are
#  OKVIS_LIBRARY, where to find the OKVIS library.

# If OKVIS_ROOT_DIR was defined in the environment, use it.
IF(NOT OKVIS_ROOT_DIR AND NOT $ENV{OKVIS_ROOT_DIR} STREQUAL "")
  SET(OKVIS_ROOT_DIR $ENV{OKVIS_ROOT_DIR})
ENDIF()

SET(_OKVIS_SEARCH_DIRS
  ${OKVIS_ROOT_DIR}
  /usr/local
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt/lib/okvis
)

FIND_PATH(OKVIS_INCLUDE_DIR
  NAMES
    okvis/DenseMatcher.hpp
  HINTS
    ${_OKVIS_SEARCH_DIRS}
  PATHS
    ${ARK_DEPENDENCY_DIR}/include
  PATH_SUFFIXES
    include
)

FIND_LIBRARY( OKVIS_CERES_LIBRARY NAMES okvis_ceres HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_COMMON_LIBRARY NAMES okvis_common HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_CV_LIBRARY NAMES okvis_cv HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_FRONTEND_LIBRARY NAMES okvis_frontend HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_KINEMATICS_LIBRARY NAMES okvis_kinematics HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_MATCHER_LIBRARY NAMES okvis_matcher HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_MULTISENSOR_PROCESSING_LIBRARY NAMES okvis_multisensor_processing HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_TIME_LIBRARY NAMES okvis_time HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_TIMING_LIBRARY NAMES okvis_timing HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )
FIND_LIBRARY( OKVIS_UTIL_LIBRARY NAMES okvis_util HINTS ${_OKVIS_SEARCH_DIRS} PATHS ${ARK_DEPENDENCY_DIR}/lib PATH_SUFFIXES lib64 lib )

IF (OKVIS_CERES_LIBRARY AND OKVIS_COMMON_LIBRARY AND OKVIS_CV_LIBRARY AND OKVIS_FRONTEND_LIBRARY AND OKVIS_KINEMATICS_LIBRARY AND OKVIS_MATCHER_LIBRARY AND OKVIS_MULTISENSOR_PROCESSING_LIBRARY AND OKVIS_TIME_LIBRARY AND OKVIS_TIMING_LIBRARY AND OKVIS_UTIL_LIBRARY AND OKVIS_INCLUDE_DIR)

   SET(OKVIS_FOUND TRUE)
   
ENDIF (OKVIS_CERES_LIBRARY AND OKVIS_COMMON_LIBRARY AND OKVIS_CV_LIBRARY AND OKVIS_FRONTEND_LIBRARY AND OKVIS_KINEMATICS_LIBRARY AND OKVIS_MATCHER_LIBRARY AND OKVIS_MULTISENSOR_PROCESSING_LIBRARY AND OKVIS_TIME_LIBRARY AND OKVIS_TIMING_LIBRARY AND OKVIS_UTIL_LIBRARY AND OKVIS_INCLUDE_DIR)

IF(OKVIS_FOUND)
  SET(OKVIS_LIBRARIES ${OKVIS_CERES_LIBRARY} ${OKVIS_COMMON_LIBRARY} ${OKVIS_CV_LIBRARY} ${OKVIS_FRONTEND_LIBRARY} ${OKVIS_KINEMATICS_LIBRARY} ${OKVIS_MATCHER_LIBRARY} ${OKVIS_MULTISENSOR_PROCESSING_LIBRARY} ${OKVIS_TIME_LIBRARY} ${OKVIS_TIMING_LIBRARY} ${OKVIS_UTIL_LIBRARY})
  SET(OKVIS_INCLUDE_DIRS ${OKVIS_INCLUDE_DIR})
  set(OKVIS_INCLUDES ${OKVIS_INCLUDE_DIRS})
  set(OKVIS_VERSION 1.11.0)
   IF (NOT REALSENSE_FIND_QUIETLY)
      MESSAGE(STATUS "Found Okvis Libraries: ${OKVIS_LIBRARIES}")
   ENDIF (NOT REALSENSE_FIND_QUIETLY)
ELSE (OKVIS_FOUND)
   # fatal error if REALSENSE is required but not found
   IF (REALSENSE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Okvis")
   ENDIF (REALSENSE_FIND_REQUIRED)
ENDIF(OKVIS_FOUND)
